# @package _global_

#### Model params #############################################################
model:
  name: gwnet
  hparams:
    hidden_size: 32
    ff_size: 256
    emb_size: 10
    n_layers: 8
    dropout: 0.3
    temporal_kernel_size: 2
    spatial_kernel_size: 2
    dilation: 2
    dilation_mod: 2
    norm: batch
    learned_adjacency: True

#### Config overrides #########################################################
dataset:
  connectivity:
    layout: csr  # set this to use efficient message-passing implementation
                 # (see https://pytorch-geometric.readthedocs.io/en/latest/advanced/sparse_tensor.html)

optimizer:
  hparams:
    lr: 0.001
    weight_decay: 0.0001
